config/routes.rb
WombatLinks::Application.routes.draw do

  root :to => 'user_links#new'
  ActiveAdmin.routes(self)

  devise_for :users do
    match "/profile" => "devise/registrations#edit", :as => :edit_user_registration, :via => [:get]
    match "/profile" => "devise/registrations#update", :as => :profile_edit, :via => [:put]
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server, :at => "/background"

  match "/links/all" => "user_links#index", :as => :all_links, :all => true
  match "/links" => "user_links#index"
  match "/link/create" => "user_links#create", :as => :create_link, :all => true
  match "/resend/:link_id" => "user_links#resend", :as => :resend_link, :via => [:get]
  match "/complain/:hash" => "requests#spam_complain", :as => :spam_complain, :via => [:get]
  match "/add_watch" => "user_watches#create_user_watch", :as => :new_user_watch, :via => [:post]

  resources :user_links
  match "/link/:id" => "user_links#show", :as => :link, :via => [:get]
  match "/link/:id" => "user_links#destroy", :as => :link_delete, :via => [:delete]

  match "/send-link" => "user_links#create", :as => :create_link, :via => [:post]

  match "/load_user_sites" => 'user_watches#user_watches_list', :method => 'post'
  match "/load_user_subscription" => 'requests#user_subscription', :method => 'post'
  match "/user_watches/:id" => 'user_watches#user_watch_destroy', :method => 'delete', :as => :user_watch

  match "/account_locked" => "requests#user_locked", :as => :user_locked
  match "/account_unlock" => "requests#send_unlock", :as => :user_unlock, :via => [:post]

  match "/wombat-rates" => "site_rates#index", :via => [:get], :as => :rates
  match "/site-rates/:id" => "site_rates#user_rates", :via => [:get], :as => :user_rates
  match "/recount-rates/:id" => "site_rates#recount_rates", :via => [:post], :as => :recount_rates

  match "/payment/" => "payments#new", :as => :payments
  match "/payment/checkout" => "payments#checkout", :via => [:post], :as => :payments_checkout
  match "/payment/confirm" => "payments#confirm", :via => [:get], :as => :payments_confirm
  match "/payment/complete" => "payments#complete", :as => :payments_complete

  match "/user_promo/create" => "payments#create_user_promo", :via => [:post], :as => :create_user_promo

  match "/about_us" => "requests#contacts", :via => [:get], :as => :contacts
  match "/send_message" => "requests#email_to_admin", :via => [:post], :as => :email_to_admin

  match "/mailing" => "requests#mailing_list_manage", :via => [:post], :as => :mailing
  match "/load_mailing" => "requests#load_mailing", :via => [:get]

  match "/terms" => "requests#terms", :via => [:get], :as => :terms

end

app/views/layouts/shared/_carousel.html.slim
#myCarousel class="carousel slide"
  .carousel-inner
    .item
      = image_tag "/img/wombats/wombat_links_1.jpg"
      //.carousel-caption
        h4 First Thumbnail label
        p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit
    .item
      = image_tag "/img/wombats/wombat_links_2.jpg"

    .item
      = image_tag "/img/wombats/wombat_links_3.jpg"

    .item
      = image_tag "/img/wombats/wombat_links_4.jpg"

    .item.active
      = image_tag "/img/wombats/wombat_links_5.jpg"

    .item
      = image_tag "/img/wombats/wombat_links_6.jpg"

    .item
      = image_tag "/img/wombats/wombat_links_7.jpg"
  a class="left carousel-control" href="#myCarousel" data-slide="prev" &lsaquo;
  a class="right carousel-control" href="#myCarousel" data-slide="next" &rsaquo;

app/views/layouts/shared/_counters.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter19389751 = new Ya.Metrika({id:19389751,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/19389751" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-37655058-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

app/views/layouts/shared/_footer.html.slim
footer
  .row
    .span6
      span#copyright
        | © #{Time.now.strftime('%Y')} WombatLinks
      br.visible-phone
      span#footer_menu
        = link_to (t 'contacts.about_us'), contacts_path
        = link_to (t 'text.terms.title'), terms_path
    .span6
      span3.pull-right
        a href="http://www.landrina.ru"
          | Landrina Projects

app/views/layouts/shared/_navigation.html.slim
a.brand href="/" WombatLinks
.nav-collapse.collapse
  ul.nav
    li.dropdown class="#{active_link_to_class(links_path, :active => [['user_links'], ['new', 'create', 'index']])}"
      a class="dropdown-toggle" data-toggle="dropdown" href="#"
        = t :links
        '
        b class="caret"
      ul.dropdown-menu
        li class="#{active_link_to_class(root_path, :active => [['user_links'], ['new', 'create']])}"
          = active_link_to (t :home_page), root_path, :active => [['user_links'], ['new', 'create']]
        - if user_signed_in?
          li class="#{active_link_to_class(links_path, :active => [['user_links'], ['index']])}"
            = active_link_to (t :my_links), links_path, :active => [['user_links'], ['index']]
        - else
          li class="#{active_link_to_class(all_links_path, :active => [['user_links'], ['index']])}"
            = active_link_to (t :all_links), all_links_path, :active => [['user_links'], ['index']]
    - if user_signed_in?
      li class="#{active_link_to_class(edit_user_registration_path, :active => [['devise/registrations'], ['edit', 'update']])}"
        = active_link_to (t :profile), edit_user_registration_path, :active => [['devise/registrations'], ['edit', 'update']]
    li class="#{active_link_to_class(rates_path, :active => [['site_rates'], ['index']])}"
      = active_link_to (t "statistics.rates.menu"), rates_path, :active => [['site_rates'], ['index']]
    li class="#{active_link_to_class(contacts_path, :active => [['requests'], ['contacts', 'email_to_admin']])}"
      = active_link_to (t "contacts.about_us"), contacts_path, :active => [['requests'], ['contacts', 'email_to_admin']]
  .navbar-form.pull-right
    - if user_signed_in?
      = t :welcome
      br
      = t :auth_tx
      span= current_user.email
      |  (
      = link_to (t :log_out), destroy_user_session_path, :method => :delete, :confirm => "Are you sure?"
      | )
    - else
      = t :welcome
      br
      span
        = active_link_to (t :sign_in), new_user_session_path, :active => :exclusive
        |  / #{active_link_to (t :sign_up), new_user_registration_path, :active => :exclusive}

app/views/layouts/shared/_news.html.slim
h3= t 'news'
- if @news_limit.count > 0
  - @news_limit.each do |news|
    h4= news.title
    p.text-info= news.text
- else
  p.text-warning= t 'messages.no_news'

app/views/layouts/shared/_plans.html.slim
#plans-and-pricing
  h3= t 'text.plans.title'

  - @plans_all.each do |plan|
    .plan
      h4= plan.name
      p
        - if plan.free?
          span.label.label-success
            strong= (t 'subscription.free')
        - else
          span.label.label-info
            strong $#{plan.price}/#{t 'month'}

      p
        = t 'subscription.sites_count'
        ' :
        = plan.sites_count
  - if !signed_in?
    - if @current_promo
      #promo
        p.text-success
          = t 'promos.registration_text'
          '
          span.month= t(:months_count, :count => @current_promo.period)
          | !
    /-else
      #promo
        - if @prepaid
          p.text-success
            = t 'promos.registration_prepaid_text'
            '
            = t(:months_count, :count => @prepaid)
            | !
  p.text-warning= t 'promos.plans_change'
  - if !is_active_link?(new_user_registration_path, :exclusive) and !signed_in?
    = button_to (t :sign_up), new_user_registration_path, class: "btn btn-large", method: :get