config/routes.rb
WombatLinks::Application.routes.draw do

  root :to => 'user_links#new'
  ActiveAdmin.routes(self)

  devise_for :users do
    match "/profile" => "devise/registrations#edit", :as => :edit_user_registration, :via => [:get]
    match "/profile" => "devise/registrations#update", :as => :profile_edit, :via => [:put]
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server, :at => "/background"

  match "/links/all" => "user_links#index", :as => :all_links, :all => true
  match "/links" => "user_links#index"
  match "/link/create" => "user_links#create", :as => :create_link, :all => true
  match "/resend/:link_id" => "user_links#resend", :as => :resend_link, :via => [:get]
  match "/complain/:hash" => "requests#spam_complain", :as => :spam_complain, :via => [:get]
  match "/add_watch" => "user_watches#create_user_watch", :as => :new_user_watch, :via => [:post]

  resources :user_links
  match "/link/:id" => "user_links#show", :as => :link, :via => [:get]
  match "/link/:id" => "user_links#destroy", :as => :link_delete, :via => [:delete]

  match "/send-link" => "user_links#create", :as => :create_link, :via => [:post]

  match "/load_user_sites" => 'user_watches#user_watches_list', :method => 'post'
  match "/load_user_subscription" => 'requests#user_subscription', :method => 'post'
  match "/user_watches/:id" => 'user_watches#user_watch_destroy', :method => 'delete', :as => :user_watch

  match "/account_locked" => "requests#user_locked", :as => :user_locked
  match "/account_unlock" => "requests#send_unlock", :as => :user_unlock, :via => [:post]

  match "/wombat-rates" => "site_rates#index", :via => [:get], :as => :rates
  match "/site-rates/:id" => "site_rates#user_rates", :via => [:get], :as => :user_rates
  match "/recount-rates/:id" => "site_rates#recount_rates", :via => [:post], :as => :recount_rates

  match "/payment/" => "payments#new", :as => :payments
  match "/payment/checkout" => "payments#checkout", :via => [:post], :as => :payments_checkout
  match "/payment/confirm" => "payments#confirm", :via => [:get], :as => :payments_confirm
  match "/payment/complete" => "payments#complete", :as => :payments_complete

  match "/user_promo/create" => "payments#create_user_promo", :via => [:post], :as => :create_user_promo

  match "/about_us" => "requests#contacts", :via => [:get], :as => :contacts
  match "/send_message" => "requests#email_to_admin", :via => [:post], :as => :email_to_admin

  match "/mailing" => "requests#mailing_list_manage", :via => [:post], :as => :mailing
  match "/load_mailing" => "requests#load_mailing", :via => [:get]

  match "/terms" => "requests#terms", :via => [:get], :as => :terms

end

app/models/user_link.rb
require 'digest/md5'
class UserLink < ActiveRecord::Base
  include PgSearch
  EMAIL_REGEXP = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  URL_REGEXP = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\Z/ix

  pg_search_scope :user_search,
                  :against => [:email, :title, :description],
                  :using => {
                      :tsearch => {:prefix => true},
                  },
                  :associated_against => {
                      :link => [:name, :title, :description],
                      :user => [:email]}

  belongs_to :user
  belongs_to :link

  validates_presence_of :email
  validates :email,
            :format => {:with => EMAIL_REGEXP},
            :if => "!email.blank?"
  validates_presence_of :link_url
  validates :link_url,
            :format => {:with => URL_REGEXP},
            :if => "!link_url.blank?"

  attr_accessible :email, :title, :description, :is_private, :is_send
  attr_protected :link_hash, :is_spam, :link_id
  attr_accessor :link_url

  before_create :set_link, :set_link_hash
  after_commit :enqueue_jobs, :on => :create

  self.per_page = 10

  def add
    if self.valid?
      set_link if !self.link_id
      set_link_hash if !self.link_hash
      self.save
    else
      false
    end
  end

  def url
    self.link.name
  end

  def get_shortened_url()
    url = self.link
    begin
      #authorize = UrlShortener::Authorize.new 'landria', 'R_de421b9f20e1012c66b13504051ce7c8'
      authorize = UrlShortener::Authorize.new Settings.bitly.login, Settings.bitly.api_key
      client = UrlShortener::Client.new authorize
      shorten = client.shorten(self.link + "?time= "+ Time.now.to_s)
    rescue RuntimeError => error
      puts "BitLy error"
      puts error.inspect
    else
      url = shorten.urls.to_s
    ensure
      return url
    end
  end

  def show_title
    return self.title.to_s if !self.title.blank?
    self.link.title.to_s
  end

  def show_description
    return self.description.to_s if !self.description.blank?
    self.link.description.to_s
  end

  def self.search(all, user_id, page, search)

    if user_id.nil?
      links = self.where(:is_private => false, :is_spam => false)
    else
      if all
        #links = self.where(((:is_private == false) && (:is_spam == false)) | (:user_id == user_id))
        links = self.where("is_private = ? AND is_spam = ? OR user_id = ?", false, false, user_id)
      else
        links = self.where(:user_id => user_id)
      end
    end

    if !search.blank?
      links = links.user_search(search.to_s)
    end

    links.order('created_at DESC').paginate(:page => page)
  end

  def user_link? user
    self.user_id == user.id
  end

  #возможо удадить
  def self.get_links_for_domain domain_name
    links = self.find_all_by_created_at(2.months.ago..Time.now)
    links.delete_if { |l| !l.link.domain_link? domain_name }
    links
  rescue
    Array.new
  end

  #удадить
  def self.get_grouped_by_link_id domain_name
    get_links_for_domain(domain_name).group_by(&:group_by_link_id)
  end

  #удадить
  def self.get_grouped_by_link_and_user domain_name
    get_grouped_by_link_id(domain_name).group_by(&:group_by_user)
  end

  def self.clear user_links
    user_links = clear_duplicates clear_spam user_links
  end

  def self.clear_spam user_links
    user_links.delete_if { |l| l.is_spam? }
    user_links
  end

  def self.clear_duplicates user_links
    user_links.each do |u_link|
      if u_link.user_id
        user_links.delete_if { |l| l.id != u_link.id and l.user_id == u_link.user_id and l.email == u_link.email and l.link_id == u_link.link_id }
      else
        user_links.delete_if { |l| l.id != u_link.id and l.email == u_link.email and l.link_id == u_link.link_id and !l.user_id }
      end
    end
    return user_links
  end

  def group_by_link_id
    self.link_id
  end

  def group_by_user
    return self.user_id if self.user_id
    self.id
  end

  def set_is_spam
    update_attribute(:is_spam, true)
  end

  def unset_is_spam
    update_attribute(:is_spam, false)
  end

  private
  def set_link_hash
    if !self.link_hash
      hash_string = "link_hash=" + self.inspect + Time.now.to_s
      hash = Digest::MD5.hexdigest hash_string
      self.link_hash = hash
    end
  end

  def set_link
    if !self.link_id
      self.link_id = Link.get_link_id self.link_url.to_s
    end
  end

  def enqueue_jobs
    Resque.enqueue(LinkJob, self.id)
  end
end

app/controllers/user_links_controller.rb
class UserLinksController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :new, :create, :resend]
  load_and_authorize_resource

  def index
    @all = params[:all]

    if user_signed_in?
      user_id = current_user.id
    else
      user_id = nil
    end

    @links = UserLink.search(@all, user_id, params[:page], params[:search])

    if !params[:search].blank?
      @search_params = params[:search]
    end

    if (!@all && !user_signed_in?)
      redirect_to all_links_path
    end
  end

# GET /links/1
  def show
    @link = UserLink.find(params[:id])

  end

# GET /links/new
  def new
    if user_signed_in? && current_user.is_locked?
      redirect_to user_locked_path
    end

    @link = UserLink.new
    if user_signed_in?
      @link.email = current_user.email
    end
  end


# GET /links/resend/:link_id
  def resend
    begin
      resend_link = UserLink.find(params[:link_id])
    rescue
      resend_link = false
    end

    if resend_link
      authorize! :resend, resend_link
      @link = UserLink.new
      if user_signed_in?
        @link.email = current_user.email
      end
      @link.link_url = resend_link.url
      @link.title = resend_link.title
      @link.description = resend_link.description

      render 'new'
    else
      redirect_to root_path, :alert => (t :link_not_found)
    end
  end

# POST /links
  def create
    @page_title = false
    link_params = params[:user_link]
    link_params = link_params.merge :user_id => current_user.id if user_signed_in?

    @link = UserLink.new(link_params)

    if @link.save
      redirect_to link_path(@link), :notice => t(:created)
    else
      render :action => "new"
    end
  end

# DELETE /links/1

# DELETE /links/1.json
  def destroy
    @link = UserLink.find(params[:id])
    @link.destroy

    redirect_to links_url
  end

end

app/views/user_links/_form.html.slim
= form_for @link, :url => create_link_path do |f|
  - if @link.errors.any?
    .alert.alert-error
      #error_explanation
        h2
          | #{t :common_error_message}
        ul
          - @link.errors.full_messages.each do |msg|
            li #{msg}
  .control-group
    .controls
      .input-prepend
        .span.add-on.hidden-phone
          i.icon-envelope
        = f.text_field :email, :class => 'input-xlarge', placeholder: 'name@wombatlinks.com'
  .control-group
    .controls
      .input-prepend
        .span.add-on.hidden-phone
          i.icon-share
        = f.text_field :link_url, :class => 'input-xlarge', placeholder: 'http://wombatlinks.com'
  .control-group
    .controls
      .input-prepend
        .span.add-on.hidden-phone
          i.icon-pencil
        = f.text_field :title, :class => 'input-xlarge', placeholder: (t :title)
  .control-group
    .controls
      .input-prepend
        .span.add-on.hidden-phone
          i.icon-pencil
        = f.text_area :description, :class => 'input-xlarge', :rows => 3, placeholder: (t :description)
  .control-group.inline
    = f.label :is_private, :class => 'control-label'
    = f.check_box :is_private, :class => 'check_box', :disabled => !signed_in?
  .form-actions
    button class="btn btn-large btn-block btn-primary" type="submit" name="commit"
      = t :send_link

app/views/user_links/_search.html.slim
.pull-right
= form_tag request.env['PATH_INFO'], :class =>"form-search" do
  .input-append
    = text_field_tag "search", '', :class =>'span3', :id => 'appendedInputButton', :placeholder => (t :search_text)
    = submit_tag (t :search) , :class => "btn", :name => nil

app/views/user_links/_twee_feed.html.slim
span#title
- if (@tweets)
  - @tweets.each do |tweet|
    article.holder_tweets
      = tweet.text
      br/
      - if(!tweet.created_at.to_s.blank?)
        span.twee-date= tweet.created_at.strftime("%Y.%m.%d %H.%M")
- else
  = t :twitter_feed_empty

app/views/user_links/index.html.slim
= title "Links"
.row
  .span5
    .page-header
      - if signed_in?
        - if (!@all)
          h1= t :my_links
          = link_to (t :all_links), all_links_path
        - else
          h1= t :all_links
          = link_to (t :my_links), links_path
      - else
        h1= t :all_links
        h5= raw t :index_auth_message, :sign_in_link => (link_to (t :sign_in_to), new_user_session_path)
    - if (!@search_params.blank?)
      span#search-results
        p
          | Результаты поиска "#{@search_params}"
  .span4.pull-right
    .page-header
      = render 'search'
.row
  .span10
    - @links.each do |link|
      - if link.is_private
        span.label.label-success
          strong= (t :is_private_show)

      - if link.is_spam
        span.label.label-important
          strong= (t :is_spam_show)
      h4
        strong
          = '#'+ link.id.to_s
          ' :
        = link_to(link.url, link.url)
      - if !link.show_title.blank?
        p= link.show_title
      span.muted
        = link.created_at.strftime("%d.%m.%Y %H:%M")
      .link_controls
        - if can? :show, link
          = link_to (t :show), link_path(link), class: 'btn btn-small'

        - if (can? :resend, link)
          = link_to (t :resend_link), resend_link_path(:link_id => link.id), class: 'btn btn-small'

        - if can? :destroy, link
          = link_to (t :destroy), link_delete_path(link), :confirm => (t :confirm), :method => :delete, class: 'btn btn-small'
      hr
    - if (@links.count == 0)
      p.text-warning= t 'messages.no_links'
  .span10
    = will_paginate @links, :renderer => BootstrapPagination::Rails
    - if can? :create, UserLink
      div
        = link_to (t :new_link), new_user_link_path, :class => "btn btn-large"

app/views/user_links/new.html.slim
= title "Link To Email Service"
.row
  .span5
    .page-header
      h1= t :new_link_title
    = render :partial => 'form'
  .span5
    .hidden-phone#mascot

app/views/user_links/show.html.slim
= title @link.show_title.blank? ? "Link to Email" : "Link: " + @link.show_title
.row
  .span5
    .page-header
      h1
        - if @link.show_title.blank?
          = (t :w_link) + @link.id.to_s
        - else
          = @link.show_title
    #link-detail
      p
        - if @link.is_private
          span.label.label-success
            strong= (t :is_private_show)
          '
        - if @link.is_spam
          span.label.label-important
            strong= (t :is_spam_show)
          '
      p
        strong
          ' URL:
        = link_to(@link.url, @link.url)
      - if !@link.show_description.blank?
        p= @link.show_description
      - if user_signed_in? && (@link.user_link? current_user)
        p
          strong
            = (t :email)
            ' :
          = @link.email
      p.muted
        = @link.created_at.strftime("%d.%m.%Y %H:%M")
      - if can? :resend, @link
        = link_to (t :resend_link), resend_link_path(:link_id => @link.id), :class => "btn"
      - if can? :destroy, @link
        = link_to (t :destroy), link_delete_path(@link), :confirm => (t :confirm), :method => :delete, :class => "btn"
      - else
        = link_to (t :all_links), all_links_path, :class => "btn"
      - if can? :add_link, UserLink
        = link_to (t :new_link), root_path, :class => "btn"