config/routes.rb
WombatLinks::Application.routes.draw do

  root :to => 'user_links#new'
  ActiveAdmin.routes(self)

  devise_for :users do
    match "/profile" => "devise/registrations#edit", :as => :edit_user_registration, :via => [:get]
    match "/profile" => "devise/registrations#update", :as => :profile_edit, :via => [:put]
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server, :at => "/background"

  match "/links/all" => "user_links#index", :as => :all_links, :all => true
  match "/links" => "user_links#index"
  match "/link/create" => "user_links#create", :as => :create_link, :all => true
  match "/resend/:link_id" => "user_links#resend", :as => :resend_link, :via => [:get]
  match "/complain/:hash" => "requests#spam_complain", :as => :spam_complain, :via => [:get]
  match "/add_watch" => "user_watches#create_user_watch", :as => :new_user_watch, :via => [:post]

  resources :user_links
  match "/link/:id" => "user_links#show", :as => :link, :via => [:get]
  match "/link/:id" => "user_links#destroy", :as => :link_delete, :via => [:delete]

  match "/send-link" => "user_links#create", :as => :create_link, :via => [:post]

  match "/load_user_sites" => 'user_watches#user_watches_list', :method => 'post'
  match "/load_user_subscription" => 'requests#user_subscription', :method => 'post'
  match "/user_watches/:id" => 'user_watches#user_watch_destroy', :method => 'delete', :as => :user_watch

  match "/account_locked" => "requests#user_locked", :as => :user_locked
  match "/account_unlock" => "requests#send_unlock", :as => :user_unlock, :via => [:post]

  match "/wombat-rates" => "site_rates#index", :via => [:get], :as => :rates
  match "/site-rates/:id" => "site_rates#user_rates", :via => [:get], :as => :user_rates
  match "/recount-rates/:id" => "site_rates#recount_rates", :via => [:post], :as => :recount_rates

  match "/payment/" => "payments#new", :as => :payments
  match "/payment/checkout" => "payments#checkout", :via => [:post], :as => :payments_checkout
  match "/payment/confirm" => "payments#confirm", :via => [:get], :as => :payments_confirm
  match "/payment/complete" => "payments#complete", :as => :payments_complete

  match "/user_promo/create" => "payments#create_user_promo", :via => [:post], :as => :create_user_promo

  match "/about_us" => "requests#contacts", :via => [:get], :as => :contacts
  match "/send_message" => "requests#email_to_admin", :via => [:post], :as => :email_to_admin

  match "/mailing" => "requests#mailing_list_manage", :via => [:post], :as => :mailing
  match "/load_mailing" => "requests#load_mailing", :via => [:get]

  match "/terms" => "requests#terms", :via => [:get], :as => :terms

end

app/models/user_watch.rb
# encoding: utf-8
class UserWatch < ActiveRecord::Base
  belongs_to :user
  belongs_to :domain

  has_many :sites_monitors, :through => :domain

  attr_accessible :user_id
  attr_accessor :url
  attr_protected :domain_id

  URL_REGEXP = /\A[A-Za-zА-ЯЁа-яё0-9]+([\-\.]{1}[A-Za-zА-ЯЁа-яё0-9]+)*\.[a-zA-ZА-ЯЁа-яё]{2,5}\Z/

  validates :url, :presence => true
  validates :user_id, :presence => true
  validates :url,
            :format => {:with => URL_REGEXP},
            :if => "!url.blank?"

  validates :domain_id, :presence => true
  validates :domain_id, :uniqueness => {:scope => :user_id}

  before_validation :set_domain_id

  private

  def set_domain_id
    self.domain_id = Domain.get_domain_id(self.url) if !self.url.blank?
  end

  def change_plan
    user = User.find(self.user_id)
    return false if !user
    user.user_plan.change_to Plan.get_suitable user.user_watch.count
  end

end

app/controllers/user_watches_controller.rb
class UserWatchesController < ApplicationController
  before_filter :check_signed_in

  def create_user_watch
    render_404 unless request.xhr?

    @user_watch = UserWatch.new(params[:user_watch].merge :user_id => current_user.id)

    if @user_watch.valid?
      @user_watch.save
      current_user.change_plan if current_user.should_change_plan?
      flash[:ajax_success] = t 'messages.user_watch.success_add'
      render :partial => "user_watches/create_user_watch", :locals => { :flash => flash }
    else
      render :partial => "user_watches/errors_user_watch", :locals => { :errors => @user_watch.errors.full_messages}
    end
  end

  def user_watches_list
    render_404 unless request.xhr?
    user_watches = UserWatch.find_all_by_user_id(current_user.id)
    render :partial => 'user_watches/list', :locals => { :sites => user_watches, :flash => flash }
  end

  def user_watch_destroy
    render_404 unless request.xhr?
    begin
      user_watch = UserWatch.find(params[:id])
      user_watch.destroy
      current_user.change_plan if current_user.should_change_plan?
      flash[:ajax_success] = t 'messages.user_watch.success_destroy'
    rescue
      flash[:ajax_alert] = t 'messages.user_watch.error_destroy'
    ensure
      render :partial => "user_watches/create_user_watch", :locals => { :flash => flash }
    end
  end

  private
  def check_signed_in
    if !signed_in?
      flash[:alert] = t 'messages.unauthorized'
      render js: %(window.location.pathname='#{root_path}') and return
    end
  end

end

app/views/user_watches/_block.html.slim
.page-header
  h2= t :watches
- if current_user.can_add_watch?
  = render :partial => "user_watches/form", :locals => { :user_watch => UserWatch.new }
#my_sites_list
  = render :partial => "user_watches/list", :locals => { :sites => current_user.sites}

app/views/user_watches/_create_user_watch.js.slim
| $("#my_sites_list").load("/load_user_sites");
| $('input[name="user_watch[url]"]').val("");
| $('form#new_user_watch .alert').remove();
| $("#subscription").load("/load_user_subscription");

app/views/user_watches/_errors_user_watch.js.slim
| $('form#new_user_watch .alert').remove();
| $('form#new_user_watch').prepend('<div class="alert alert-error"></div>');
| $("form#new_user_watch .alert-error").append('<div id="error_explanation"></div>');
| $("form#new_user_watch .alert-error #error_explanation").append('<h2>#{t :common_error_message}</h2>');
| $("form#new_user_watch .alert-error #error_explanation").append('<ul></ul>');
- errors.each do |err|
 | $("form#new_user_watch .alert-error #error_explanation ul").append("<li>#{err}</li>");

app/views/user_watches/_form.html.slim
#my-sites
  = form_for user_watch, :url => new_user_watch_path, :remote => true do |f|
    .input-prepend
      .span.add-on
        i.icon-plus-sign
      = f.text_field :url, :class => 'input-xlarge', :placeholder => 'wombatlinks.com'
      button class="btn" type="submit" name="commit"
        = t :add_site

app/views/user_watches/_list.html.slim
- if flash[:ajax_alert] or flash[:ajax_success]
  = bootstrap_flash
- sites.each do |site|
  .site-item
    i.icon-ok
    span
      = site.domain.name
    .btn.btn-mini.btn-link
      = link_to (t :destroy), site, :confirm => (t :confirm_site_delete), :method => :delete, :remote => true

    - if current_user.stats_accessible?
      .btn.btn-mini.btn-link
        = link_to (t 'statistics.show_stats'), user_rates_path(site.domain_id)

app/views/user_watches/_redirect.js.slim
| window.location = #{root_path}

app/views/user_watches/_user_watches_list.slim
- if @user_watches.count >0
  ul
    - @user_watches.each do |watch|
      = watch.domain