config/routes.rb
WombatLinks::Application.routes.draw do

  root :to => 'user_links#new'
  ActiveAdmin.routes(self)

  devise_for :users do
    match "/profile" => "devise/registrations#edit", :as => :edit_user_registration, :via => [:get]
    match "/profile" => "devise/registrations#update", :as => :profile_edit, :via => [:put]
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server, :at => "/background"

  match "/links/all" => "user_links#index", :as => :all_links, :all => true
  match "/links" => "user_links#index"
  match "/link/create" => "user_links#create", :as => :create_link, :all => true
  match "/resend/:link_id" => "user_links#resend", :as => :resend_link, :via => [:get]
  match "/complain/:hash" => "requests#spam_complain", :as => :spam_complain, :via => [:get]
  match "/add_watch" => "user_watches#create_user_watch", :as => :new_user_watch, :via => [:post]

  resources :user_links
  match "/link/:id" => "user_links#show", :as => :link, :via => [:get]
  match "/link/:id" => "user_links#destroy", :as => :link_delete, :via => [:delete]

  match "/send-link" => "user_links#create", :as => :create_link, :via => [:post]

  match "/load_user_sites" => 'user_watches#user_watches_list', :method => 'post'
  match "/load_user_subscription" => 'requests#user_subscription', :method => 'post'
  match "/user_watches/:id" => 'user_watches#user_watch_destroy', :method => 'delete', :as => :user_watch

  match "/account_locked" => "requests#user_locked", :as => :user_locked
  match "/account_unlock" => "requests#send_unlock", :as => :user_unlock, :via => [:post]

  match "/wombat-rates" => "site_rates#index", :via => [:get], :as => :rates
  match "/site-rates/:id" => "site_rates#user_rates", :via => [:get], :as => :user_rates
  match "/recount-rates/:id" => "site_rates#recount_rates", :via => [:post], :as => :recount_rates

  match "/payment/" => "payments#new", :as => :payments
  match "/payment/checkout" => "payments#checkout", :via => [:post], :as => :payments_checkout
  match "/payment/confirm" => "payments#confirm", :via => [:get], :as => :payments_confirm
  match "/payment/complete" => "payments#complete", :as => :payments_complete

  match "/user_promo/create" => "payments#create_user_promo", :via => [:post], :as => :create_user_promo

  match "/about_us" => "requests#contacts", :via => [:get], :as => :contacts
  match "/send_message" => "requests#email_to_admin", :via => [:post], :as => :email_to_admin

  match "/mailing" => "requests#mailing_list_manage", :via => [:post], :as => :mailing
  match "/load_mailing" => "requests#load_mailing", :via => [:get]

  match "/terms" => "requests#terms", :via => [:get], :as => :terms

end

app/models/site_rate.rb
require "rate"
require "rate_move"
require 'hpricot'
require 'net/http'

class SiteRate < ActiveRecord::Base
  extend Rate
  include RateMove

  attr_accessible :domain_id, :prev_month, :prev_week, :this_month, :this_week
  attr_protected :total, :position, :prev_position

  belongs_to :domain

  self.per_page = 20

  def recount_rates
    links = UserLink.clear self.links

    links_total = Array.new(links)
    links_total.keep_if { |l| l.created_at >= self.updated_at }

    links_t_week = Array.new(links)
    links_t_week.keep_if { |l| l.created_at >= 7.days.ago }

    links_t_month = Array.new(links)
    links_t_month.keep_if { |l| l.created_at >= 1.months.ago }

    links_p_week = Array.new(links)
    links_p_week.keep_if { |l| l.created_at >= 14.days.ago and l.created_at < 7.days.ago }

    links_p_month = Array.new(links)
    links_p_month.keep_if { |l| l.created_at >= 2.months.ago and l.created_at < 1.months.ago }

    self.update_attributes this_week: links_t_week.count, this_month: links_t_month.count, prev_week: links_p_week.count, prev_month: links_p_month.count
    self.update_attribute(:total, (self.total + links_total.count))
  end

  def links
    self.domain.user_link
  end

  def self.get_rates page
    self.where('total > 0').order('total DESC').paginate(:page => page)
  end

  def self.get_alexa_rank
    SiteRate.all.each do |sr|
      begin
        url = 'http://data.alexa.com/data?cli=10&dat=snbamz&url=' + sr.domain.name
        response = Net::HTTP.get_response(URI.parse(URI.encode(url)))
        xml = response.body

        doc = Hpricot::XML(xml)
        sr.update_attribute :alexa, doc.at(:POPULARITY)['TEXT']
      rescue
      end
    end
  end
end

app/controllers/site_rates_controller.rb
class SiteRatesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  load_and_authorize_resource

  def index
    @rates = SiteRate.get_rates params[:page]
  end

  def user_rates
    @rates = SiteRate.find(params[:id])
    @link_rates = LinkRate.get_rates @rates.domain.id, params[:page]
  end

  def recount_rates
    render_404 unless request.xhr?
    Resque.enqueue(RecountUserStatsJob, params[:id])
    flash[:notice] = (t :task_enqueued)
    render :js => "window.location = '#{user_rates_path(params[:id])}'"
  end
end

app/views/site_rates/_rates.html.slim
.span10
  - if rates.count > 0
    table.table.table-striped
      thead
        tr
          th= t 'statistics.rates.position'
          - if rates.first.is_a? SiteRate
            th= t 'statistics.rates.site'
          - else
            th= t 'link'
          th= t 'statistics.rates.this_week'
          th= t 'statistics.rates.this_month'
          th= t 'statistics.rates.total'
          - if rates.first.is_a? SiteRate
            th Alexa Rank
      tbody
        - rates.each do |rate|
          tr
            td
              = rate.position
              span.stats class="#{rate.p_move_sign}"
                - if rate.p_move.to_i > 0
                  i.icon-chevron-up
                - if rate.p_move.to_i < 0
                  i.icon-chevron-down
                = rate.p_move.abs if rate.p_move
            td
              - if rate.is_a? SiteRate
                = link_to rate.domain.name, rate.domain.url, :target => "_blank"
              - else
                = link_to rate.link.name, rate.link.name, :target => "_blank"
            td
              = rate.this_week
              span.stats class="#{rate.w_move_sign}"
                - if rate.w_move.to_i > 0
                  i.icon-chevron-up
                - if rate.w_move.to_i < 0
                  i.icon-chevron-down
                = rate.w_move.abs if rate.w_move
            td
              = rate.this_month
              span.stats class="#{rate.m_move_sign}"
                - if rate.m_move.to_i > 0
                  i.icon-chevron-up
                - if rate.m_move.to_i < 0
                  i.icon-chevron-down
                = rate.m_move.abs if rate.m_move
            td= rate.total
            - if rate.is_a? SiteRate
              td= rate.alexa
  - else
    p.text-warning= t 'messages.no_data'
.span10
  = will_paginate rates, :renderer => BootstrapPagination::Rails

app/views/site_rates/index.html.slim
= title "WombatRates"
h2= t "statistics.rates.title"
.row
  = render :partial => 'site_rates/rates', locals: {rates: @rates}

app/views/site_rates/user_rates.html.slim
= title "User WombatRates"
- if @rates
  h2 WombatRates
  h3
    = link_to @rates.domain.name, @rates.domain.url, :target => '_blank'
  = button_to (t 'statistics.recount_rates'), recount_rates_path(@rates.id), :method => :post, :remote => true, :class => 'btn'

  h5= t 'statistics.uptime', :uptime => @rates.domain.uptime

  .row
    .span10
      table.table.table-striped
        thead
          tr
            th= t 'statistics.rates.position'
            th= t 'statistics.rates.this_week'
            th= t 'statistics.rates.this_month'
            th= t 'statistics.rates.total'
            th Alexa Rank
        tbody
          tr
            td
              = @rates.position
              span.stats class="#{@rates.p_move_sign}"
                - if @rates.p_move.to_i > 0
                  i.icon-chevron-up
                - if @rates.p_move.to_i < 0
                  i.icon-chevron-down
                = @rates.p_move.abs if @rates.p_move
            td
              = @rates.this_week
              span.stats class="#{@rates.w_move_sign}"
                - if @rates.w_move.to_i > 0
                  i.icon-chevron-up
                - if @rates.w_move.to_i < 0
                  i.icon-chevron-down
                = @rates.w_move.abs if @rates.w_move
            td
              = @rates.this_month
              span.stats class="#{@rates.m_move_sign}"
                - if @rates.m_move.to_i > 0
                  i.icon-chevron-up
                - if @rates.m_move.to_i < 0
                  i.icon-chevron-down
                = @rates.m_move.abs if @rates.m_move
            td= @rates.total
            td= @rates.alexa

  h3= t 'statistics.rates.pages_title'
  .row
    = render :partial => 'site_rates/rates', locals: {rates: @link_rates}